/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package kiesample;

import com.brightd.cashflow.Person;

global java.util.ArrayList persons;

rule "rule 1" when
    m : Person( );
then
    m.setHappy(true);
    System.out.println( "[idrools rule1] " + m.getName() + ",  " +  m.getAge());
end

rule "rule 2" when
    p: Person( name == "HAL" )
then
    p.setHappy(true);
    System.out.println( "[idrools rule2] ");
end


rule "rule 3" when
    p: Person( name == "HAL2" )
then
    p.setHappy(true);
    persons.add(p);
        System.out.println( "[idrools rule3] ");
end